#!/bin/bash

echo "Офаем стандартный файрволл"
systemctl disable firewalld #удаляем из автозагрузки firewalld
systemctl stop firewalld #выключаем firewalld
echo "Ставим другой фаерволл"
dnf install -q -y iptables-services #устанавливаем iptables 
cp ./iptables /etc/sysconfig/iptables #копируем настройки фаерволла
systemctl restart iptables #рестартуем фаерволл
systemctl enable iptables #включаем в автозагрузку
#Выключение Selinux
sed -i 's/^SELINUX=.*/SELINUX=disabled/g' /etc/selinux/config  #изменяем положение селинукс
setenforce 0 #выключаем селинукс
#установка докера
echo "Ставим докер"
sudo yum install -q -y yum-utils 
sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
sudo yum install -q -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin #добавление репозитория
systemctl start docker #стартуем докер
systemctl enable docker #включаем докер в автозагрузку
echo "Ставим слейв MySQL"
docker pull -q mysql/mysql-server:8.0 #скачиваем образ MySQL
docker run -d --name=slave_mysql --hostname=slave -v $PWD/d1:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=mypass mysql/mysql-server:8.0 --server-id=2  #запускаем контейнер со слейвом
echo "Слейв установлен"
